[package]
name = "p"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
owo-colors = "4.1"
regex = "1.10"
anyhow = "1.0"
itertools = "0.13"
unicode-width = "0.1"
crossterm = "0.27"
glob = "0.3"
